In [1]:
from __future__ import print_function, division

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy

In [2]:
device = torch.device('cpu')
model = torch.load('model.pth', map_location=device)
#model.eval()

#model = Net()
#model.load_state_dict(torch.load('model.pth', map_location=device))
model.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (8): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU(inplace=True)
    (11): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (13): ReLU(inplace=True)
    (14): MaxPool2d(ke

In [3]:
from PIL import Image
from torchvision import transforms
im = Image.open("Datasets/Test/Aedes_albopictus/0_2_Aa_100.JPG")

preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

img = preprocess(im)
img = img.unsqueeze(0)

In [4]:
labels = np.array(open("class.txt").read().splitlines())

In [5]:
labels

array(['Aedes_albopictus', 'Aedes_vexans', 'Anopheles_sinensis',
       'Culex_pipiens', 'Culex_tritaeniorhynchus', 'Non_vectors'],
      dtype='<U23')

In [6]:

pred = model(img)

In [7]:
pred

tensor([[ 2.5480,  2.0888, -1.2224, -0.0110, -1.3486, -1.3253]],
       grad_fn=<AddmmBackward>)

In [24]:
labels[torch.argmax(pred).numpy().tolist()]

'Aedes_albopictus'

In [8]:
pred[0]

tensor([ 2.5480,  2.0888, -1.2224, -0.0110, -1.3486, -1.3253],
       grad_fn=<SelectBackward>)

In [10]:
pred[0].detach().numpy()

array([ 2.5480402 ,  2.0887957 , -1.2224208 , -0.01097421, -1.3486404 ,
       -1.3252932 ], dtype=float32)

In [12]:
import pandas as pd
df = pd.DataFrame({'class':labels, 'probability':pred[0].detach().numpy()})

In [13]:
df

class  probability
0         Aedes_albopictus     2.548040
1             Aedes_vexans     2.088796
2       Anopheles_sinensis    -1.222421
3            Culex_pipiens    -0.010974
4  Culex_tritaeniorhynchus    -1.348640
5              Non_vectors    -1.325293